application: 'squashtai'
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/
  static_dir: images

- url: /js/
  static_dir: js

- url: /css/
  static_dir: css

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /.*
  script: main.py
